services:
    Tbn\BoilerplateBundle\Command\MakeBoilerplateCommand:
        public: true
        class: "Tbn\\BoilerplateBundle\\Command\\MakeBoilerplateCommand"
        arguments:
            - '@twig'
            - '%kernel.project_dir%'
            - '%tbn.boilerplate.template_keys%'
            - '%tbn.boilerplate.templates%'
        tags:
            - { name: 'console.command', command: 'make:boilerplate' }
